import { LLMProvider } from "./type";

export const DEFAULT_LLM_MODELS: Record<LLMProvider, string> = {
  [LLMProvider.OPENAI]: "gpt-4o-mini",
  [LLMProvider.CLAUDE]: "claude-sonnet-4-6",
  [LLMProvider.GEMINI]: "gemini-2.0-flash",
  [LLMProvider.OPENROUTER]: "anthropic/claude-sonnet-4.6",
  [LLMProvider.OLLAMA]: "llama3.2",
};

// Maximum number of extra columns for campaigns, campaign profiles, resources, and resource groups.
export const NUMBER_OF_COLUMN = 30;
export const DEFAULT_MCP_PORT = 53535;

/** Shared key for campaign config, workflow, database, and resource config export/import so files can be shared between users. */
export const FILE_KEY = "67keeperA@";

export const PLATFORM_SOL_WALLET =
  "ELGTTNvs4AwAcKKdpMqBdSbFU5Nw9mDwHF7sFvLAMp3d";
export const PLATFORM_EVM_WALLET = "0x3dbc7856d635b8576241e572532b40c18dd8badf";
export const PLATFORM_SWAP_FEE_BPS = 5; // 0.05%

export const SOL_MINT_ADDRESS = "So11111111111111111111111111111111111111112";
export const USD1_MINT_ADDRESS_ON_SOLANA =
  "USD1ttGY1N17NEEHLmELoaybftRBUSErhqYiQzvEmuB";

export const MESSAGE = {
  // WalletGroup
  CREATE_WALLET_GROUP: "CREATE_WALLET_GROUP",
  CREATE_WALLET_GROUP_RES: "CREATE_WALLET_GROUP_RES",
  GET_LIST_WALLET_GROUP: "GET_LIST_WALLET_GROUP",
  GET_LIST_WALLET_GROUP_RES: "GET_LIST_WALLET_GROUP_RES",
  GET_ONE_WALLET_GROUP: "GET_ONE_WALLET_GROUP",
  GET_ONE_WALLET_GROUP_RES: "GET_ONE_WALLET_GROUP_RES",
  UPDATE_WALLET_GROUP: "UPDATE_WALLET_GROUP",
  UPDATE_WALLET_GROUP_RES: "UPDATE_WALLET_GROUP_RES",
  DELETE_WALLET_GROUP: "DELETE_WALLET_GROUP",
  DELETE_WALLET_GROUP_RES: "DELETE_WALLET_GROUP_RES",
  GET_WALLET_GROUP_DEPENDENCY: "GET_WALLET_GROUP_DEPENDENCY",
  GET_WALLET_GROUP_DEPENDENCY_RES: "GET_WALLET_GROUP_DEPENDENCY_RES",

  // Wallet
  IMPORT_WALLET: "IMPORT_WALLET",
  IMPORT_WALLET_RES: "IMPORT_WALLET_RES",
  EXPORT_WALLET: "EXPORT_WALLET",
  EXPORT_WALLET_RES: "EXPORT_WALLET_RES",
  CREATE_WALLET: "CREATE_WALLET",
  CREATE_WALLET_RES: "CREATE_WALLET_RES",
  GET_LIST_WALLET: "GET_LIST_WALLET",
  GET_LIST_WALLET_RES: "GET_LIST_WALLET_RES",
  DELETE_WALLET: "DELETE_WALLET",
  DELETE_WALLET_RES: "DELETE_WALLET_RES",
  UPDATE_WALLET: "UPDATE_WALLET",
  UPDATE_WALLET_RES: "UPDATE_WALLET_RES",
  GENERATE_RANDOM_WALLET: "GENERATE_RANDOM_WALLET",
  GENERATE_RANDOM_WALLET_RES: "GENERATE_RANDOM_WALLET_RES",
  GENERATE_WALLET_FROM_PHRASE: "GENERATE_WALLET_FROM_PHRASE",
  GENERATE_WALLET_FROM_PHRASE_RES: "GENERATE_WALLET_FROM_PHRASE_RES",

  // Resource
  IMPORT_RESOURCE: "IMPORT_RESOURCE",
  IMPORT_RESOURCE_RES: "IMPORT_RESOURCE_RES",
  EXPORT_RESOURCE: "EXPORT_RESOURCE",
  EXPORT_RESOURCE_RES: "EXPORT_RESOURCE_RES",
  CREATE_RESOURCE: "CREATE_RESOURCE",
  CREATE_RESOURCE_RES: "CREATE_RESOURCE_RES",
  GET_LIST_RESOURCE: "GET_LIST_RESOURCE",
  GET_LIST_RESOURCE_RES: "GET_LIST_RESOURCE_RES",
  UPDATE_RESOURCE: "UPDATE_RESOURCE",
  UPDATE_RESOURCE_RES: "UPDATE_RESOURCE_RES",
  DELETE_RESOURCE: "DELETE_RESOURCE",
  DELETE_RESOURCE_RES: "DELETE_RESOURCE_RES",

  // Resource group
  CREATE_RESOURCE_GROUP: "CREATE_RESOURCE_GROUP",
  CREATE_RESOURCE_GROUP_RES: "CREATE_RESOURCE_GROUP_RES",
  GET_LIST_RESOURCE_GROUP: "GET_LIST_RESOURCE_GROUP",
  GET_LIST_RESOURCE_GROUP_RES: "GET_LIST_RESOURCE_GROUP_RES",
  GET_ONE_RESOURCE_GROUP: "GET_ONE_RESOURCE_GROUP",
  GET_ONE_RESOURCE_GROUP_RES: "GET_ONE_RESOURCE_GROUP_RES",
  UPDATE_RESOURCE_GROUP: "UPDATE_RESOURCE_GROUP",
  UPDATE_RESOURCE_GROUP_RES: "UPDATE_RESOURCE_GROUP_RES",
  DELETE_RESOURCE_GROUP: "DELETE_RESOURCE_GROUP",
  DELETE_RESOURCE_GROUP_RES: "DELETE_RESOURCE_GROUP_RES",
  EXPORT_RESOURCE_GROUP: "EXPORT_RESOURCE_GROUP",
  EXPORT_RESOURCE_GROUP_RES: "EXPORT_RESOURCE_GROUP_RES",
  IMPORT_RESOURCE_GROUP: "IMPORT_RESOURCE_GROUP",
  IMPORT_RESOURCE_GROUP_RES: "IMPORT_RESOURCE_GROUP_RES",

  // Profile group
  CREATE_PROFILE_GROUP: "CREATE_PROFILE_GROUP",
  CREATE_PROFILE_GROUP_RES: "CREATE_PROFILE_GROUP_RES",
  GET_LIST_PROFILE_GROUP: "GET_LIST_PROFILE_GROUP",
  GET_LIST_PROFILE_GROUP_RES: "GET_LIST_PROFILE_GROUP_RES",
  GET_ONE_PROFILE_GROUP: "GET_ONE_PROFILE_GROUP",
  GET_ONE_PROFILE_GROUP_RES: "GET_ONE_PROFILE_GROUP_RES",
  UPDATE_PROFILE_GROUP: "UPDATE_PROFILE_GROUP",
  UPDATE_PROFILE_GROUP_RES: "UPDATE_PROFILE_GROUP_RES",
  DELETE_PROFILE_GROUP: "DELETE_PROFILE_GROUP",
  DELETE_PROFILE_GROUP_RES: "DELETE_PROFILE_GROUP_RES",

  // Profile
  CREATE_PROFILE: "CREATE_PROFILE",
  CREATE_PROFILE_RES: "CREATE_PROFILE_RES",
  GET_LIST_PROFILE: "GET_LIST_PROFILE",
  GET_LIST_PROFILE_RES: "GET_LIST_PROFILE_RES",
  UPDATE_PROFILE: "UPDATE_PROFILE",
  UPDATE_PROFILE_RES: "UPDATE_PROFILE_RES",
  DELETE_PROFILE: "DELETE_PROFILE",
  DELETE_PROFILE_RES: "DELETE_PROFILE_RES",
  EXPORT_PROFILE: "EXPORT_PROFILE",
  EXPORT_PROFILE_RES: "EXPORT_PROFILE_RES",

  // Extension
  IMPORT_EXTENSION: "IMPORT_EXTENSION",
  IMPORT_EXTENSION_RES: "IMPORT_EXTENSION_RES",
  CANCEL_IMPORT_EXTENSION: "CANCEL_IMPORT_EXTENSION",
  GET_LIST_EXTENSION: "GET_LIST_EXTENSION",
  GET_LIST_EXTENSION_RES: "GET_LIST_EXTENSION_RES",
  GET_LIST_EXTENSIONB_BY_NAME: "GET_LIST_EXTENSIONB_BY_NAME",
  GET_LIST_EXTENSIONB_BY_NAME_RES: "GET_LIST_EXTENSIONB_BY_NAME_RES",
  DELETE_EXTENSION: "DELETE_EXTENSION",
  DELETE_EXTENSION_RES: "DELETE_EXTENSION_RES",
  GET_EXTENSION_ID_ON_BROWSER: "GET_EXTENSION_ID_ON_BROWSER",
  GET_EXTENSION_ID_ON_BROWSER_RES: "GET_EXTENSION_ID_ON_BROWSER_RES",
  CREATE_BASE_PROFILE_EXTENSION: "CREATE_BASE_PROFILE_EXTENSION",
  CREATE_BASE_PROFILE_EXTENSION_RES: "CREATE_BASE_PROFILE_EXTENSION_RES",

  // Workflow
  GET_LIST_WORKFLOW_RES: "GET_LIST_WORKFLOW_RES",
  GET_LIST_WORKFLOW: "GET_LIST_WORKFLOW",
  GET_ONE_WORKFLOW_RES: "GET_ONE_WORKFLOW_RES",
  GET_ONE_WORKFLOW: "GET_ONE_WORKFLOW",
  DELETE_WORKFLOW_RES: "DELETE_WORKFLOW_RES",
  DELETE_WORKFLOW: "DELETE_WORKFLOW",
  UPDATE_WORKFLOW_RES: "UPDATE_WORKFLOW_RES",
  UPDATE_WORKFLOW: "UPDATE_WORKFLOW",
  CREATE_WORKFLOW_RES: "CREATE_WORKFLOW_RES",
  CREATE_WORKFLOW: "CREATE_WORKFLOW",
  EXPORT_WORKFLOW: "EXPORT_WORKFLOW",
  EXPORT_WORKFLOW_RES: "EXPORT_WORKFLOW_RES",
  IMPORT_WORKFLOW: "IMPORT_WORKFLOW",
  IMPORT_WORKFLOW_RES: "IMPORT_WORKFLOW_RES",

  // Campaign
  GET_LIST_CAMPAIGN_RES: "GET_LIST_CAMPAIGN_RES",
  GET_LIST_CAMPAIGN: "GET_LIST_CAMPAIGN",
  GET_ONE_CAMPAIGN_RES: "GET_ONE_CAMPAIGN_RES",
  GET_ONE_CAMPAIGN: "GET_ONE_CAMPAIGN",
  DELETE_CAMPAIGN_RES: "DELETE_CAMPAIGN_RES",
  DELETE_CAMPAIGN: "DELETE_CAMPAIGN",
  UPDATE_CAMPAIGN_RES: "UPDATE_CAMPAIGN_RES",
  UPDATE_CAMPAIGN: "UPDATE_CAMPAIGN",
  CREATE_CAMPAIGN_RES: "CREATE_CAMPAIGN_RES",
  CREATE_CAMPAIGN: "CREATE_CAMPAIGN",
  DELETE_JOB_RELATED_TO_CAMPAIGN_RES: "DELETE_JOB_RELATED_TO_CAMPAIGN_RES",
  SYNC_CAMPAIGN_PROFILE: "SYNC_CAMPAIGN_PROFILE",
  SYNC_CAMPAIGN_PROFILE_RES: "SYNC_CAMPAIGN_PROFILE_RES",
  EXPORT_CAMPAIGN_PROFILE: "EXPORT_CAMPAIGN_PROFILE",
  EXPORT_CAMPAIGN_PROFILE_RES: "EXPORT_CAMPAIGN_PROFILE_RES",
  EXPORT_CAMPAIGN: "EXPORT_CAMPAIGN",
  EXPORT_CAMPAIGN_RES: "EXPORT_CAMPAIGN_RES",
  IMPORT_CAMPAIGN: "IMPORT_CAMPAIGN",
  IMPORT_CAMPAIGN_RES: "IMPORT_CAMPAIGN_RES",

  // CampaignProfile
  GET_LIST_CAMPAIGN_PROFILE_RES: "GET_LIST_CAMPAIGN_PROFILE_RES",
  GET_LIST_CAMPAIGN_PROFILE: "GET_LIST_CAMPAIGN_PROFILE",
  DELETE_CAMPAIGN_PROFILE_RES: "DELETE_CAMPAIGN_PROFILE_RES",
  DELETE_CAMPAIGN_PROFILE: "DELETE_CAMPAIGN_PROFILE",
  DELETE_CAMPAIGN_PROFILE_PROGRESS_RES: "DELETE_CAMPAIGN_PROFILE_PROGRESS_RES",
  UPDATE_CAMPAIGN_PROFILE_RES: "UPDATE_CAMPAIGN_PROFILE_RES",
  UPDATE_CAMPAIGN_PROFILE: "UPDATE_CAMPAIGN_PROFILE",
  PICK_CAMPAIGN_PROFILE_TO_RUN: "PICK_CAMPAIGN_PROFILE_TO_RUN",
  PICK_CAMPAIGN_PROFILE_TO_RUN_RES: "PICK_CAMPAIGN_PROFILE_TO_RUN_RES",
  UPDATE_LIST_CAMPAIGN_PROFILE_RES: "UPDATE_LIST_CAMPAIGN_PROFILE_RES",
  UPDATE_LIST_CAMPAIGN_PROFILE: "UPDATE_LIST_CAMPAIGN_PROFILE",
  OPEN_CAMPAIGN_PROFILE_IN_BROWSER: "OPEN_CAMPAIGN_PROFILE_IN_BROWSER",
  OPEN_CAMPAIGN_PROFILE_IN_BROWSER_RES: "OPEN_CAMPAIGN_PROFILE_IN_BROWSER_RES",
  CLOSE_CAMPAIGN_PROFILE_IN_BROWSER: "CLOSE_CAMPAIGN_PROFILE_IN_BROWSER",
  CLOSE_CAMPAIGN_PROFILE_IN_BROWSER_RES:
    "CLOSE_CAMPAIGN_PROFILE_IN_BROWSER_RES",
  DELETE_PROFILE_FOLDER_PROGRESS_RES: "DELETE_PROFILE_FOLDER_PROGRESS_RES",
  GET_CAMPAIGN_PROFILE_STATUS: "GET_CAMPAIGN_PROFILE_STATUS",
  GET_CAMPAIGN_PROFILE_STATUS_RES: "GET_CAMPAIGN_PROFILE_STATUS_RES",
  GET_CAMPAIGN_PROFILE_CALCULATED_VALUE:
    "GET_CAMPAIGN_PROFILE_CALCULATED_VALUE",
  GET_CAMPAIGN_PROFILE_CALCULATED_VALUE_RES:
    "GET_CAMPAIGN_PROFILE_CALCULATED_VALUE_RES",
  GET_CAMPAIGN_PROFILE_COLUMN_STATS: "GET_CAMPAIGN_PROFILE_COLUMN_STATS",
  GET_CAMPAIGN_PROFILE_COLUMN_STATS_RES:
    "GET_CAMPAIGN_PROFILE_COLUMN_STATS_RES",

  // StaticProxyGroup
  CREATE_PROXY_GROUP: "CREATE_PROXY_GROUP",
  CREATE_PROXY_GROUP_RES: "CREATE_PROXY_GROUP_RES",
  GET_LIST_PROXY_GROUP: "GET_LIST_PROXY_GROUP",
  GET_LIST_PROXY_GROUP_RES: "GET_LIST_PROXY_GROUP_RES",
  GET_ONE_PROXY_GROUP: "GET_ONE_PROXY_GROUP",
  GET_ONE_PROXY_GROUP_RES: "GET_ONE_PROXY_GROUP_RES",
  UPDATE_PROXY_GROUP: "UPDATE_PROXY_GROUP",
  UPDATE_PROXY_GROUP_RES: "UPDATE_PROXY_GROUP_RES",
  DELETE_PROXY_GROUP: "DELETE_PROXY_GROUP",
  DELETE_PROXY_GROUP_RES: "DELETE_PROXY_GROUP_RES",

  // StaticProxy
  CREATE_PROXY: "CREATE_PROXY",
  CREATE_PROXY_RES: "CREATE_PROXY_RES",
  GET_LIST_PROXY: "GET_LIST_PROXY",
  GET_LIST_PROXY_RES: "GET_LIST_PROXY_RES",
  DELETE_PROXY: "DELETE_PROXY",
  DELETE_PROXY_RES: "DELETE_PROXY_RES",
  UPDATE_PROXY: "UPDATE_PROXY",
  UPDATE_PROXY_RES: "UPDATE_PROXY_RES",

  // NodeEndpointGroup
  CREATE_NODE_ENDPOINT_GROUP: "CREATE_NODE_ENDPOINT_GROUP",
  CREATE_NODE_ENDPOINT_GROUP_RES: "CREATE_NODE_ENDPOINT_GROUP_RES",
  GET_LIST_NODE_ENDPOINT_GROUP: "GET_LIST_NODE_ENDPOINT_GROUP",
  GET_LIST_NODE_ENDPOINT_GROUP_RES: "GET_LIST_NODE_ENDPOINT_GROUP_RES",
  GET_ONE_NODE_ENDPOINT_GROUP: "GET_ONE_NODE_ENDPOINT_GROUP",
  GET_ONE_NODE_ENDPOINT_GROUP_RES: "GET_ONE_NODE_ENDPOINT_GROUP_RES",
  UPDATE_NODE_ENDPOINT_GROUP: "UPDATE_NODE_ENDPOINT_GROUP",
  UPDATE_NODE_ENDPOINT_GROUP_RES: "UPDATE_NODE_ENDPOINT_GROUP_RES",
  DELETE_NODE_ENDPOINT_GROUP: "DELETE_NODE_ENDPOINT_GROUP",
  DELETE_NODE_ENDPOINT_GROUP_RES: "DELETE_NODE_ENDPOINT_GROUP_RES",

  // NodeEndpoint
  CREATE_NODE_ENDPOINT: "CREATE_NODE_ENDPOINT",
  CREATE_NODE_ENDPOINT_RES: "CREATE_NODE_ENDPOINT_RES",
  GET_LIST_NODE_ENDPOINT: "GET_LIST_NODE_ENDPOINT",
  GET_LIST_NODE_ENDPOINT_RES: "GET_LIST_NODE_ENDPOINT_RES",
  DELETE_NODE_ENDPOINT: "DELETE_NODE_ENDPOINT",
  DELETE_NODE_ENDPOINT_RES: "DELETE_NODE_ENDPOINT_RES",
  UPDATE_NODE_ENDPOINT: "UPDATE_NODE_ENDPOINT",
  UPDATE_NODE_ENDPOINT_RES: "UPDATE_NODE_ENDPOINT_RES",

  // Label
  CREATE_LABEL: "CREATE_LABEL",
  CREATE_LABEL_RES: "CREATE_LABEL_RES",
  GET_LIST_LABEL: "GET_LIST_LABEL",
  GET_LIST_LABEL_RES: "GET_LIST_LABEL_RES",
  GET_ONE_LABEL: "GET_ONE_LABEL",
  GET_ONE_LABEL_RES: "GET_ONE_LABEL_RES",
  DELETE_LABEL: "DELETE_LABEL",
  DELETE_LABEL_RES: "DELETE_LABEL_RES",
  UPDATE_LABEL: "UPDATE_LABEL",
  UPDATE_LABEL_RES: "UPDATE_LABEL_RES",

  GET_LIST_APP_LOG: "GET_LIST_APP_LOG",
  GET_LIST_APP_LOG_RES: "GET_LIST_APP_LOG_RES",
  CREATE_APP_LOG: "CREATE_APP_LOG",
  CREATE_APP_LOG_RES: "CREATE_APP_LOG_RES",
  DELETE_APP_LOG: "DELETE_APP_LOG",
  DELETE_APP_LOG_RES: "DELETE_APP_LOG_RES",

  // Window
  ENTER_FULL_SCREEN: "ENTER_FULL_SCREEN",
  EXIT_FULL_SCREEN: "EXIT_FULL_SCREEN",
  GET_SCREEN_SIZE: "GET_SCREEN_SIZE",
  GET_SCREEN_SIZE_RES: "GET_SCREEN_SIZE_RES",
  CHECK_DEVICE_TYPE: "CHECK_DEVICE_TYPE",
  CHECK_DEVICE_TYPE_RES: "CHECK_DEVICE_TYPE_RES",

  // Preference
  INIT_PREFERENCE: "INIT_PREFERENCE",
  GET_ONE_PREFERENCE: "GET_LIST_PREFERENCE",
  GET_ONE_PREFERENCE_RES: "GET_ONE_PREFERENCE_RES",
  UPDATE_PREFERENCE: "UPDATE_PREFERENCE",
  UPDATE_PREFERENCE_RES: "UPDATE_PREFERENCE_RES",

  // Telegram bot
  RESTART_TELEGRAM_BOT: "RESTART_TELEGRAM_BOT",

  // WhatsApp
  RESTART_WHATSAPP: "RESTART_WHATSAPP",
  WHATSAPP_QR: "WHATSAPP_QR",
  WHATSAPP_STATUS: "WHATSAPP_STATUS",

  // Database
  EXPORT_DATABASE: "EXPORT_DATABASE",
  EXPORT_DATABASE_RES: "EXPORT_DATABASE_RES",
  IMPORT_DATABASE: "IMPORT_DATABASE",
  IMPORT_DATABASE_RES: "IMPORT_DATABASE_RES",

  // Dialog
  CHOOSE_FOLDER: "CHOOSE_FOLDER",
  CHOOSE_FOLDER_RES: "CHOOSE_FOLDER_RES",
  CHOOSE_FILE: "CHOOSE_FILE",
  CHOOSE_FILE_RES: "CHOOSE_FILE_RES",
  READ_FILE_AS_DATA_URL: "READ_FILE_AS_DATA_URL",
  READ_FILE_AS_DATA_URL_RES: "READ_FILE_AS_DATA_URL_RES",
  SAVE_CLIPBOARD_IMAGE: "SAVE_CLIPBOARD_IMAGE",
  SAVE_CLIPBOARD_IMAGE_RES: "SAVE_CLIPBOARD_IMAGE_RES",
  DELETE_TEMP_FILE: "DELETE_TEMP_FILE",
  DELETE_TEMP_FILE_RES: "DELETE_TEMP_FILE_RES",
  OPEN_FOLDER: "OPEN_FOLDER",
  OPEN_FOLDER_RES: "OPEN_FOLDER_RES",
  CHECK_MODEL_CAPABILITY: "CHECK_MODEL_CAPABILITY",
  CHECK_MODEL_CAPABILITY_RES: "CHECK_MODEL_CAPABILITY_RES",
  CHECK_CLAUDE_CLI_AVAILABLE: "CHECK_CLAUDE_CLI_AVAILABLE",
  CHECK_CLAUDE_CLI_AVAILABLE_RES: "CHECK_CLAUDE_CLI_AVAILABLE_RES",

  // Data statistic
  GET_STATISTIC: "GET_STATISTIC",
  GET_STATISTIC_RES: "GET_STATISTIC_RES",

  // Folder statistic
  GET_PROFILE_FOLDER_STATISTIC: "GET_PROFILE_FOLDER_STATISTIC",
  GET_PROFILE_FOLDER_STATISTIC_RES: "GET_PROFILE_FOLDER_STATISTIC_RES",
  GET_EXTENSION_FOLDER_STATISTIC: "GET_EXTENSION_FOLDER_STATISTIC",
  GET_EXTENSION_FOLDER_STATISTIC_RES: "GET_EXTENSION_FOLDER_STATISTIC_RES",
  GET_TEMP_FOLDER_STATISTIC: "GET_TEMP_FOLDER_STATISTIC",
  GET_TEMP_FOLDER_STATISTIC_RES: "GET_TEMP_FOLDER_STATISTIC_RES",
  GET_SKILL_FOLDER_STATISTIC: "GET_SKILL_FOLDER_STATISTIC",
  GET_SKILL_FOLDER_STATISTIC_RES: "GET_SKILL_FOLDER_STATISTIC_RES",
  GET_BROWSER_FOLDER_STATISTIC: "GET_BROWSER_FOLDER_STATISTIC",
  GET_BROWSER_FOLDER_STATISTIC_RES: "GET_BROWSER_FOLDER_STATISTIC_RES",
  GET_DATABASE_FILE_STATISTIC: "GET_DATABASE_FILE_STATISTIC",
  GET_DATABASE_FILE_STATISTIC_RES: "GET_DATABASE_FILE_STATISTIC_RES",

  GET_FOLDER_PATH: "GET_FOLDER_PATH",
  GET_FOLDER_PATH_RES: "GET_FOLDER_PATH_RES",

  // Download browser
  DOWNLOAD_BROWSER: "DOWNLOAD_BROWSER",
  DOWNLOAD_BROWSER_RES: "DOWNLOAD_BROWSER_RES",
  CHECK_BROWSER_INSTALLED: "CHECK_BROWSER_INSTALLED",
  CHECK_BROWSER_INSTALLED_RES: "CHECK_BROWSER_INSTALLED_RES",

  // Other
  OPEN_PORTFOLIO_APP_RES: "OPEN_PORTFOLIO_APP_RES",
  OPEN_EXTERNAL_LINK: "OPEN_EXTERNAL_LINK",
  LOG: "LOG",
  LOG_BATCH: "LOG_BATCH",

  // Schedule
  CREATE_SCHEDULE: "CREATE_SCHEDULE",
  CREATE_SCHEDULE_RES: "CREATE_SCHEDULE_RES",
  UPDATE_SCHEDULE: "UPDATE_SCHEDULE",
  UPDATE_SCHEDULE_RES: "UPDATE_SCHEDULE_RES",
  RUNNING_SCHEDULE_JOB_RES: "RUNNING_SCHEDULE_JOB_RES",
  DELETE_SCHEDULE: "DELETE_SCHEDULE",
  DELETE_SCHEDULE_RES: "DELETE_SCHEDULE_RES",
  GET_LIST_SCHEDULE: "GET_LIST_SCHEDULE",
  GET_LIST_SCHEDULE_RES: "GET_LIST_SCHEDULE_RES",
  GET_ONE_SCHEDULE: "GET_ONE_SCHEDULE",
  GET_ONE_SCHEDULE_RES: "GET_ONE_SCHEDULE_RES",
  JOB_TO_RUN: "JOB_TO_RUN",

  // Job
  DELETE_JOB: "DELETE_JOB",
  DELETE_JOB_RES: "DELETE_JOB_RES",
  UPDATE_JOB: "UPDATE_JOB",
  UPDATE_JOB_RES: "UPDATE_JOB_RES",
  MARK_JOB_COMPLETED: "MARK_JOB_COMPLETED",
  MARK_JOB_COMPLETED_RES: "MARK_JOB_COMPLETED_RES",
  CHECK_JOB_EXISTED: "CHECK_JOB_EXISTED",
  CHECK_JOB_EXISTED_RES: "CHECK_JOB_EXISTED_RES",

  // NodeSecret — per-node secret key stored encrypted in DB, never stored them in Workflow data or Redux for security purpose
  UPSERT_NODE_SECRET: "UPSERT_NODE_SECRET",
  UPSERT_NODE_SECRET_RES: "UPSERT_NODE_SECRET_RES",
  GET_NODE_SECRET: "GET_NODE_SECRET",
  GET_NODE_SECRET_RES: "GET_NODE_SECRET_RES",

  RUN_SCHEDULE_NOW: "RUN_SCHEDULE_NOW",
  RUN_SCHEDULE_NOW_RES: "RUN_SCHEDULE_NOW_RES",
  GET_RUNNING_AGENT_SCHEDULE: "GET_RUNNING_AGENT_SCHEDULE",
  GET_RUNNING_AGENT_SCHEDULE_RES: "GET_RUNNING_AGENT_SCHEDULE_RES",

  GET_GOOGLE_AUTH_CODE: "GET_GOOGLE_AUTH_CODE",
  SAVE_USER_EMAIL: "SAVE_USER_EMAIL",
  SAVE_USER_EMAIL_RES: "SAVE_USER_EMAIL_RES",
  SETUP_MASTER_PASSWORD: "SETUP_MASTER_PASSWORD",
  SETUP_MASTER_PASSWORD_RES: "SETUP_MASTER_PASSWORD_RES",
  VERIFY_MASTER_PASSWORD: "VERIFY_MASTER_PASSWORD",
  VERIFY_MASTER_PASSWORD_RES: "VERIFY_MASTER_PASSWORD_RES",
  CHECK_MASTER_PASSWORD_EXISTS: "CHECK_MASTER_PASSWORD_EXISTS",
  CHECK_MASTER_PASSWORD_EXISTS_RES: "CHECK_MASTER_PASSWORD_EXISTS_RES",
  RESET_MASTER_PASSWORD: "RESET_MASTER_PASSWORD",
  RESET_MASTER_PASSWORD_RES: "RESET_MASTER_PASSWORD_RES",
  GET_SAMPLE_CONTRACT_SNIPER_RESULT: "GET_SAMPLE_CONTRACT_SNIPER_RESULT",
  GET_SAMPLE_CONTRACT_SNIPER_RESULT_RES:
    "GET_SAMPLE_CONTRACT_SNIPER_RESULT_RES",
  RUN_JAVASCRIPT_CODE: "RUN_JAVASCRIPT_CODE",
  RUN_JAVASCRIPT_CODE_RES: "RUN_JAVASCRIPT_CODE_RES",
  GET_PRICE_CHECKING_DATA: "GET_PRICE_CHECKING_DATA",
  GET_PRICE_CHECKING_DATA_RES: "GET_PRICE_CHECKING_DATA_RES",
  GET_MARKETCAP_CHECKING_DATA: "GET_MARKETCAP_CHECKING_DATA",
  GET_MARKETCAP_CHECKING_DATA_RES: "GET_MARKETCAP_CHECKING_DATA_RES",

  // Workflow
  WORKFLOW_BATCH_UPDATE: "WORKFLOW_BATCH_UPDATE",
  SCRIPT_RUN_COMPLETED: "SCRIPT_RUN_COMPLETED",
  TERMINATE_THREAD: "TERMINATE_THREAD",
  TERMINATE_THREAD_RES: "TERMINATE_THREAD_RES",
  SCRIPT_RESULT_RES: "SCRIPT_RESULT_RES",
  START_WORKFLOW: "START_WORKFLOW",
  START_WORKFLOW_RES: "START_WORKFLOW_RES",
  STOP_WORKFLOW: "STOP_WORKFLOW",
  STOP_WORKFLOW_RES: "STOP_WORKFLOW_RES",
  STOP_ALL_WORKFLOW: "STOP_ALL_WORKFLOW",
  STOP_ALL_WORKFLOW_RES: "STOP_ALL_WORKFLOW_RES",
  WORKFLOW_THREAD_STOPPED: "WORKFLOW_THREAD_STOPPED",
  WORKFLOW_HAS_NEW_ROUND: "WORKFLOW_HAS_NEW_ROUND",
  WORKFLOW_SLEEPING_STATUS: "WORKFLOW_SLEEPING_STATUS",
  WORKFLOW_SYNC_DATA_TO_UI: "WORKFLOW_SYNC_DATA_TO_UI",
  WORKFLOW_SYNC_DATA_TO_UI_RES: "WORKFLOW_SYNC_DATA_TO_UI_RES",
  GET_LIST_RUNNING_WORKFLOW: "GET_LIST_RUNNING_WORKFLOW",
  GET_LIST_RUNNING_WORKFLOW_RES: "GET_LIST_RUNNING_WORKFLOW_RES",
  GET_USER_PERMISSIONS: "GET_USER_PERMISSIONS",
  GET_USER_PERMISSIONS_RES: "GET_USER_PERMISSIONS_RES",

  // Encrypt key cache
  GET_ENCRYPT_KEY_CACHE: "GET_ENCRYPT_KEY_CACHE",
  GET_ENCRYPT_KEY_CACHE_RES: "GET_ENCRYPT_KEY_CACHE_RES",
  SET_ENCRYPT_KEY_CACHE: "SET_ENCRYPT_KEY_CACHE",
  SET_ENCRYPT_KEY_CACHE_RES: "SET_ENCRYPT_KEY_CACHE_RES",

  // Search
  GLOBAL_SEARCH: "GLOBAL_SEARCH",
  GLOBAL_SEARCH_RES: "GLOBAL_SEARCH_RES",

  // Dashboard agent
  DASHBOARD_AGENT_CREATE_SESSION: "DASHBOARD_AGENT_CREATE_SESSION",
  DASHBOARD_AGENT_CREATE_SESSION_RES: "DASHBOARD_AGENT_CREATE_SESSION_RES",
  DASHBOARD_AGENT_READY: "DASHBOARD_AGENT_READY",
  DASHBOARD_AGENT_GET_STATUS: "DASHBOARD_AGENT_GET_STATUS",
  DASHBOARD_AGENT_GET_STATUS_RES: "DASHBOARD_AGENT_GET_STATUS_RES",
  DASHBOARD_AGENT_RUN: "DASHBOARD_AGENT_RUN",
  DASHBOARD_AGENT_RUN_RES: "DASHBOARD_AGENT_RUN_RES",
  DASHBOARD_AGENT_STREAM_CHUNK: "DASHBOARD_AGENT_STREAM_CHUNK",
  DASHBOARD_AGENT_TOOL_START: "DASHBOARD_AGENT_TOOL_START",
  DASHBOARD_AGENT_TOOL_COMPLETE: "DASHBOARD_AGENT_TOOL_COMPLETE",
  DASHBOARD_AGENT_TOOL_PROGRESS: "DASHBOARD_AGENT_TOOL_PROGRESS",
  DASHBOARD_AGENT_RESET_SESSION: "DASHBOARD_AGENT_RESET_SESSION",
  DASHBOARD_AGENT_RESET_SESSION_RES: "DASHBOARD_AGENT_RESET_SESSION_RES",
  DASHBOARD_AGENT_STOP: "DASHBOARD_AGENT_STOP",
  DASHBOARD_AGENT_STOP_RES: "DASHBOARD_AGENT_STOP_RES",
  DASHBOARD_AGENT_CHANGE_PROVIDER: "DASHBOARD_AGENT_CHANGE_PROVIDER",
  DASHBOARD_AGENT_CHANGE_PROVIDER_RES: "DASHBOARD_AGENT_CHANGE_PROVIDER_RES",
  DASHBOARD_AGENT_PLAN_REVIEW: "DASHBOARD_AGENT_PLAN_REVIEW",
  DASHBOARD_AGENT_PLAN_APPROVAL: "DASHBOARD_AGENT_PLAN_APPROVAL",
  DASHBOARD_AGENT_STEP_ADVANCED: "DASHBOARD_AGENT_STEP_ADVANCED",

  // Chat History (persistent agent memory across sessions)
  CHAT_HISTORY_SAVE_MESSAGE: "CHAT_HISTORY_SAVE_MESSAGE",
  CHAT_HISTORY_SAVE_MESSAGE_RES: "CHAT_HISTORY_SAVE_MESSAGE_RES",
  CHAT_HISTORY_LOAD: "CHAT_HISTORY_LOAD",
  CHAT_HISTORY_LOAD_RES: "CHAT_HISTORY_LOAD_RES",
  CHAT_HISTORY_CLEAR: "CHAT_HISTORY_CLEAR",
  CHAT_HISTORY_CLEAR_RES: "CHAT_HISTORY_CLEAR_RES",

  // MCP Server
  GET_LIST_MCP_SERVER: "GET_LIST_MCP_SERVER",
  GET_LIST_MCP_SERVER_RES: "GET_LIST_MCP_SERVER_RES",
  CREATE_MCP_SERVER: "CREATE_MCP_SERVER",
  CREATE_MCP_SERVER_RES: "CREATE_MCP_SERVER_RES",
  UPDATE_MCP_SERVER: "UPDATE_MCP_SERVER",
  UPDATE_MCP_SERVER_RES: "UPDATE_MCP_SERVER_RES",
  DELETE_MCP_SERVER: "DELETE_MCP_SERVER",
  DELETE_MCP_SERVER_RES: "DELETE_MCP_SERVER_RES",
  GET_MCP_SERVER_TOOLS: "GET_MCP_SERVER_TOOLS",
  GET_MCP_SERVER_TOOLS_RES: "GET_MCP_SERVER_TOOLS_RES",
  MCP_SERVER_STATUS_UPDATED: "MCP_SERVER_STATUS_UPDATED",

  // Agent Skill
  GET_LIST_AGENT_SKILL: "GET_LIST_AGENT_SKILL",
  GET_LIST_AGENT_SKILL_RES: "GET_LIST_AGENT_SKILL_RES",
  CREATE_AGENT_SKILL: "CREATE_AGENT_SKILL",
  CREATE_AGENT_SKILL_RES: "CREATE_AGENT_SKILL_RES",
  UPDATE_AGENT_SKILL: "UPDATE_AGENT_SKILL",
  UPDATE_AGENT_SKILL_RES: "UPDATE_AGENT_SKILL_RES",
  DELETE_AGENT_SKILL: "DELETE_AGENT_SKILL",
  DELETE_AGENT_SKILL_RES: "DELETE_AGENT_SKILL_RES",

  // Agent Setting
  GET_LIST_AGENT_SETTING: "GET_LIST_AGENT_SETTING",
  GET_LIST_AGENT_SETTING_RES: "GET_LIST_AGENT_SETTING_RES",
  CREATE_AGENT_SETTING: "CREATE_AGENT_SETTING",
  CREATE_AGENT_SETTING_RES: "CREATE_AGENT_SETTING_RES",
  UPDATE_AGENT_SETTING: "UPDATE_AGENT_SETTING",
  UPDATE_AGENT_SETTING_RES: "UPDATE_AGENT_SETTING_RES",
  DELETE_AGENT_SETTING: "DELETE_AGENT_SETTING",
  DELETE_AGENT_SETTING_RES: "DELETE_AGENT_SETTING_RES",

  // Auth safe storage
  GET_AUTH_STATE: "GET_AUTH_STATE",
  GET_AUTH_STATE_RES: "GET_AUTH_STATE_RES",
  SAVE_AUTH_TOKEN: "SAVE_AUTH_TOKEN",
  CLEAR_AUTH_TOKEN: "CLEAR_AUTH_TOKEN",

  // Agent profile
  GET_LIST_AGENT_PROFILE: "GET_LIST_AGENT_PROFILE",
  GET_LIST_AGENT_PROFILE_RES: "GET_LIST_AGENT_PROFILE_RES",
  GET_ONE_AGENT_PROFILE: "GET_ONE_AGENT_PROFILE",
  GET_ONE_AGENT_PROFILE_RES: "GET_ONE_AGENT_PROFILE_RES",
  CREATE_AGENT_PROFILE: "CREATE_AGENT_PROFILE",
  CREATE_AGENT_PROFILE_RES: "CREATE_AGENT_PROFILE_RES",
  UPDATE_AGENT_PROFILE: "UPDATE_AGENT_PROFILE",
  UPDATE_AGENT_PROFILE_RES: "UPDATE_AGENT_PROFILE_RES",
  DELETE_AGENT_PROFILE: "DELETE_AGENT_PROFILE",
  DELETE_AGENT_PROFILE_RES: "DELETE_AGENT_PROFILE_RES",
  GET_AGENT_PROFILE_MEMORY: "GET_AGENT_PROFILE_MEMORY",
  GET_AGENT_PROFILE_MEMORY_RES: "GET_AGENT_PROFILE_MEMORY_RES",
  SAVE_AGENT_PROFILE_MEMORY: "SAVE_AGENT_PROFILE_MEMORY",
  SAVE_AGENT_PROFILE_MEMORY_RES: "SAVE_AGENT_PROFILE_MEMORY_RES",
  GET_LIST_AGENT_PROFILE_LOG: "GET_LIST_AGENT_PROFILE_LOG",
  GET_LIST_AGENT_PROFILE_LOG_RES: "GET_LIST_AGENT_PROFILE_LOG_RES",

  // Agent profile chat session
  AGENT_PROFILE_CREATE_SESSION: "AGENT_PROFILE_CREATE_SESSION",
  AGENT_PROFILE_CREATE_SESSION_RES: "AGENT_PROFILE_CREATE_SESSION_RES",
  AGENT_PROFILE_READY: "AGENT_PROFILE_READY",
  AGENT_PROFILE_RUN: "AGENT_PROFILE_RUN",
  AGENT_PROFILE_RUN_RES: "AGENT_PROFILE_RUN_RES",
  AGENT_PROFILE_STREAM_CHUNK: "AGENT_PROFILE_STREAM_CHUNK",
  AGENT_PROFILE_TOOL_START: "AGENT_PROFILE_TOOL_START",
  AGENT_PROFILE_TOOL_COMPLETE: "AGENT_PROFILE_TOOL_COMPLETE",
  AGENT_PROFILE_TOOL_PROGRESS: "AGENT_PROFILE_TOOL_PROGRESS",
  AGENT_PROFILE_STOP: "AGENT_PROFILE_STOP",
  AGENT_PROFILE_STOP_RES: "AGENT_PROFILE_STOP_RES",
  AGENT_PROFILE_RESET_SESSION: "AGENT_PROFILE_RESET_SESSION",
  AGENT_PROFILE_RESET_SESSION_RES: "AGENT_PROFILE_RESET_SESSION_RES",
  AGENT_PROFILE_STEP_ADVANCED: "AGENT_PROFILE_STEP_ADVANCED",

  // Keeper MCP Token
  GET_LIST_MCP_TOKEN: "GET_LIST_MCP_TOKEN",
  GET_LIST_MCP_TOKEN_RES: "GET_LIST_MCP_TOKEN_RES",
  CREATE_MCP_TOKEN: "CREATE_MCP_TOKEN",
  CREATE_MCP_TOKEN_RES: "CREATE_MCP_TOKEN_RES",
  DELETE_MCP_TOKEN: "DELETE_MCP_TOKEN",
  DELETE_MCP_TOKEN_RES: "DELETE_MCP_TOKEN_RES",
  MCP_CONNECTIONS_UPDATED: "MCP_CONNECTIONS_UPDATED",
  INSTALL_TO_CLAUDE_CODE: "INSTALL_TO_CLAUDE_CODE",
  INSTALL_TO_CLAUDE_CODE_RES: "INSTALL_TO_CLAUDE_CODE_RES",

  // Agent Task
  GET_LIST_AGENT_TASK: "GET_LIST_AGENT_TASK",
  GET_LIST_AGENT_TASK_RES: "GET_LIST_AGENT_TASK_RES",
  GET_ONE_AGENT_TASK: "GET_ONE_AGENT_TASK",
  GET_ONE_AGENT_TASK_RES: "GET_ONE_AGENT_TASK_RES",
  CREATE_AGENT_TASK: "CREATE_AGENT_TASK",
  CREATE_AGENT_TASK_RES: "CREATE_AGENT_TASK_RES",
  UPDATE_AGENT_TASK: "UPDATE_AGENT_TASK",
  UPDATE_AGENT_TASK_RES: "UPDATE_AGENT_TASK_RES",
  DELETE_AGENT_TASK: "DELETE_AGENT_TASK",
  DELETE_AGENT_TASK_RES: "DELETE_AGENT_TASK_RES",
  AGENT_TASK_CHANGED: "AGENT_TASK_CHANGED",
  AGENT_MAILBOX_CHANGED: "AGENT_MAILBOX_CHANGED",
  AGENT_TASK_ASSIGNED: "AGENT_TASK_ASSIGNED",
  GET_AGENT_ANALYTICS: "GET_AGENT_ANALYTICS",
  GET_AGENT_ANALYTICS_RES: "GET_AGENT_ANALYTICS_RES",
};

//  Log level for UI coloring (e.g. system log viewer)
export enum LOG_TYPE {
  ERROR = "error",
  SUCCESS = "success",
  WARNING = "warning",
  INFO = "info",
  DIM = "dim",
}

export enum WORKFLOW_TYPE {
  // Launch token
  LAUNCH_TOKEN_PUMPFUN = "LAUNCH_TOKEN_PUMPFUN",
  LAUNCH_TOKEN_BONKFUN = "LAUNCH_TOKEN_BONKFUN",

  // Agent
  GENERATE_IMAGE = "GENERATE_IMAGE",
  RUN_AGENT = "RUN_AGENT",

  // Browser
  OPEN_URL = "OPEN_URL",
  CLICK = "CLICK",
  NEW_TAB = "NEW_TAB",
  SELECT_TAB = "SELECT_TAB",
  CLOSE_TAB = "CLOSE_TAB",
  GO_BACK = "GO_BACK",
  RELOAD_PAGE = "RELOAD_PAGE",
  TYPE_TEXT = "TYPE_TEXT",
  EXECUTE_CODE = "EXECUTE_CODE",
  HTTP_REQUEST = "HTTP_REQUEST",
  SCROLL = "SCROLL",
  SWITCH_WINDOW = "SWITCH_WINDOW",
  SOLVE_CAPTCHA = "SOLVE_CAPTCHA",
  CRAWL_TEXT = "CRAWL_TEXT",
  CHECK_ELEMENT_EXIST = "CHECK_ELEMENT_EXIST",
  CLICK_EXTENSION = "CLICK_EXTENSION",
  UPLOAD_FILE = "UPLOAD_FILE",

  // Onchain
  GET_WALLET_BALANCE = "GET_WALLET_BALANCE",
  SELECT_TOKEN = "SELECT_TOKEN",
  SELECT_CHAIN = "SELECT_CHAIN",
  TRANSFER_TOKEN = "TRANSFER_TOKEN",
  EVM_APPROVE_REVOKE_TOKEN = "EVM_APPROVE_REVOKE_TOKEN",
  SWAP_UNISWAP = "SWAP_UNISWAP",
  SWAP_PANCAKESWAP = "SWAP_PANCAKESWAP",
  SWAP_CETUS = "SWAP_CETUS",
  SWAP_KYBERSWAP = "SWAP_KYBERSWAP",
  SWAP_JUPITER = "SWAP_JUPITER",
  GET_TOKEN_PRICE = "GET_TOKEN_PRICE",
  CHECK_TOKEN_PRICE = "CHECK_TOKEN_PRICE",
  CHECK_MARKETCAP = "CHECK_MARKETCAP",
  EVM_SNIPE_CONTRACT = "EVM_SNIPE_CONTRACT",
  EXECUTE_TRANSACTION = "EXECUTE_TRANSACTION",
  CONVERT_TOKEN_AMOUNT = "CONVERT_TOKEN_AMOUNT",
  SELECT_WALLET = "SELECT_WALLET",
  CHECK_RESOURCE = "CHECK_RESOURCE",
  STOP_SCRIPT = "STOP_SCRIPT",
  EVM_READ_FROM_CONTRACT = "EVM_READ_FROM_CONTRACT",
  EVM_WRITE_TO_CONTRACT = "EVM_WRITE_TO_CONTRACT",
  GET_GAS_PRICE = "GET_GAS_PRICE",
  GET_PRIORITY_FEE = "GET_PRIORITY_FEE",
  GENERATE_VANITY_ADDRESS = "GENERATE_VANITY_ADDRESS",

  // Telgram
  SEND_TELEGRAM = "SEND_TELEGRAM",
  SNIPE_TELEGRAM = "SNIPE_TELEGRAM",

  // Twitter
  LOGIN_TWITTER = "LOGIN_TWITTER",
  FOLLOW_TWITTER = "FOLLOW_TWITTER",
  LIKE_TWITTER = "LIKE_TWITTER",
  RETWEET_TWITTER = "RETWEET_TWITTER",
  REPLY_TWITTER = "REPLY_TWITTER",

  // Metamask wallet
  IMPORT_METAMASK_WALLET = "IMPORT_METAMASK_WALLET",
  UNLOCK_METAMASK_WALLET = "UNLOCK_METAMASK_WALLET",
  CONNECT_METAMASK_WALLET = "CONNECT_METAMASK_WALLET",
  APPROVE_METAMASK_WALLET = "APPROVE_METAMASK_WALLET",
  CONFIRM_METAMASK_WALLET = "CONFIRM_METAMASK_WALLET",
  CANCEL_METAMASK_WALLET = "CANCEL_METAMASK_WALLET",

  // Rabby wallet
  IMPORT_RABBY_WALLET = "IMPORT_RABBY_WALLET",
  UNLOCK_RABBY_WALLET = "UNLOCK_RABBY_WALLET",
  CONNECT_RABBY_WALLET = "CONNECT_RABBY_WALLET",
  CANCEL_RABBY_WALLET = "CANCEL_RABBY_WALLET",
  SIGN_RABBY_WALLET = "SIGN_RABBY_WALLET",
  ADD_NETWORK_RABBY_WALLET = "ADD_NETWORK_RABBY_WALLET",

  // Martian wallet
  IMPORT_MARTIAN_WALLET = "IMPORT_MARTIAN_WALLET",
  UNLOCK_MARTIAN_WALLET = "UNLOCK_MARTIAN_WALLET",
  APPROVE_MARTIAN_WALLET = "APPROVE_MARTIAN_WALLET",
  SWITCH_MARTIAN_WALLET = "SWITCH_MARTIAN_WALLET",

  // Phantom wallet
  IMPORT_PHANTOM_WALLET = "IMPORT_PHANTOM_WALLET",
  UNLOCK_PHANTOM_WALLET = "UNLOCK_PHANTOM_WALLET",
  CONNECT_PHANTOM_WALLET = "CONNECT_PHANTOM_WALLET",
  CLICK_CONFIRM_PHANTOM_WALLET = "CLICK_CONFIRM_PHANTOM_WALLET",

  // Other
  COMMENT = "COMMENT",
  GENERATE_PROFILE = "GENERATE_PROFILE",
  SET_ATTRIBUTE = "SET_ATTRIBUTE",
  CHECK_CONDITION = "CHECK_CONDITION",
  GET_RANDOM_VALUE = "GET_RANDOM_VALUE",
  RANDOM_ON_OFF = "RANDOM_ON_OFF",
  CALCULATE = "CALCULATE",
  SAVE_WALLET = "SAVE_WALLET",
  SAVE_RESOURCE = "SAVE_RESOURCE",
  UPDATE_PROFILE = "UPDATE_PROFILE",
  ON_OFF_PROFILE = "ON_OFF_PROFILE",
  SAVE_LOG = "SAVE_LOG",
  LOOP = "LOOP",
  DEBATE = "DEBATE",
  CHECKPOINT = "CHECKPOINT",
}

export const RESPONSE_CODE = {
  // valiedate file
  INVALID_FILE_TYPE: "INVALID_FILE_TYPE",
  NOT_EXTENSION: "NOT_EXTENSION",
  DATABASE_ERROR: "DATABASE_ERROR",
  READ_FILE_ERROR: "READ_FILE_ERROR",
  OBJECT_EXISTED: "OBJECT_EXISTED",
  NORMAL_MESSAGE: "NORMAL_MESSAGE",

  // validate database
  DUPLICATE_ERROR: "DUPLICATE_ERROR",

  SUCCESS: "SUCCESS",
  ERROR: "ERROR",
};

export const FILE_PROTOCOL_NAME = "media";
export const EXTENSION_FOLDER = "ka_extension";
export const TEMP_FOLDER = "ka_temp";
export const PROFILE_FOLDER = "ka_profile";
export const BROWSER_FOLDER = "ka_browser";
export const BASE_PROFILE_FOLDER = "base_profile";
export const KA_SKILL_FOLDER = "ka_skill";
export const KA_WORKSPACE_FOLDER = "ka_workspace";
export const KA_MEMORY_FOLDER = "ka_memory";

export const FILE_TYPE = {
  TXT: "txt",
  XLSX: "xlsx",
  ZIP: "zip",
  CRX: "crx",
};

export enum SELECTOR_TYPE {
  CSS_SELECTOR = "CSS_SELECTOR",
  XPATH_SELECTOR = "XPATH_SELECTOR",
}

export enum SCROLL_TYPE {
  SCROLL_SELECTOR = "SCROLL_SELECTOR",
  SCROLL_COORDINATES = "SCROLL_COORDINATES",
}

export enum SCROLL_DIRECTION {
  SCROLL_UP = "SCROLL_UP",
  SCROLL_DOWN = "SCROLL_DOWN",
}

export const SELECTOR_NAME = {
  [SELECTOR_TYPE.CSS_SELECTOR]: "CSS selector",
  [SELECTOR_TYPE.XPATH_SELECTOR]: "XPath selector",
};

export const SCROLL_TYPE_NAME = {
  [SCROLL_TYPE.SCROLL_SELECTOR]: "Selector",
  [SCROLL_TYPE.SCROLL_COORDINATES]: "Coordinates",
};

export const SCROLL_DIRECTION_NAME = {
  [SCROLL_DIRECTION.SCROLL_UP]: "Up",
  [SCROLL_DIRECTION.SCROLL_DOWN]: "Down",
};

export enum TOKEN_TYPE {
  NATIVE_TOKEN = "NATIVE_TOKEN", // use for di  fferent chain type
  EVM_ERC20_TOKEN = "EVM_ERC20_TOKEN",
  APTOS_COIN = "APTOS_COIN",
  SUI_COIN = "SUI_COIN",
  SOLANA_TOKEN = "SOLANA_TOKEN",
}

export const TOKEN_TYPE_NAME = {
  [TOKEN_TYPE.NATIVE_TOKEN]: "Native token",
  [TOKEN_TYPE.EVM_ERC20_TOKEN]: "ERC20 token",
  [TOKEN_TYPE.APTOS_COIN]: "Coin",
  [TOKEN_TYPE.SUI_COIN]: "Coin",
  [TOKEN_TYPE.SOLANA_TOKEN]: "Token",
};
export enum POOL_TYPE {
  UNISWAP_V2_POOL = "UNISWAP_V2_POOL",
  UNISWAP_V3_POOL = "UNISWAP_V3_POOL",
  UNISWAP_V4_POOL = "UNISWAP_V4_POOL",
  PANCAKESWAP_V2_POOL = "PANCAKESWAP_V2_POOL",
  PANCAKESWAP_V3_POOL = "PANCAKESWAP_V3_POOL",
  PANCAKESWAP_INFINITY_CL_POOL = "PANCAKESWAP_INFINITY_CL_POOL",
  PANCAKESWAP_INFINITY_BIN_POOL = "PANCAKESWAP_INFINITY_BIN_POOL",
}
export enum EVM_TRANSACTION_TYPE {
  LEGACY = "LEGACY",
  EIP_1559 = "EIP_1559",
}

export enum RANDOM_OPTION {
  RANDOM_NUMBER = "RANDOM_NUMBER",
  RANDOM_VALUE = "RANDOM_VALUE",
}

export enum SET_ATTRIBUTE_MODE {
  BASIC = "BASIC",
  ADVANCED = "ADVANCED",
}

export enum CHAIN_TYPE {
  EVM = "EVM",
  APTOS = "APTOS",
  SUI = "SUI",
  SOLANA = "SOLANA",
  TON = "TON",
}

export const CHAIN_TYPE_NAME_EN = {
  [CHAIN_TYPE.EVM]: "EVM - most popular",
  [CHAIN_TYPE.SOLANA]: "Solana",
  [CHAIN_TYPE.APTOS]: "Aptos",
  [CHAIN_TYPE.SUI]: "Sui",
};

export const TYPE_NAME = {
  WALLET: "WALLET",
  WALLET_GROUP: "WALLET_GROUP",
  RESOURCE: "RESOURCE",
  RESOURCE_GROUP: "RESOURCE_GROUP",
  PROFILE: "PROFILE",
  PROFILE_GROUP: "PROFILE_GROUP",
  EXTENSION: "EXTENSION",
  PROXY: "PROXY",
};

export enum WINDOW_TYPE {
  MAIN_WINDOW = "MAIN_WINDOW",
  POPUP_WINDOW = "POPUP_WINDOW",
}

export enum CAPTCHA_TYPE {
  RECAPTCHAV2 = "RECAPTCHAV2",
  HCAPTCHA = "HCAPTCHA",
  TURNSTILE_CLOUDFLARE = "TURNSTILE_CLOUDFLARE",
}

export const PORTFOLIO_APP = {
  DEBANK: "DEBANK",
  SUI_VISION: "SUI_VISION",
  APTOS_EXPLORER: "APTOS_EXPLORER",
  SOL_SCAN: "SOL_SCAN",
};

export const PORTFOLIO_APP_NAME = {
  [PORTFOLIO_APP.DEBANK]: "DeBank",
  [PORTFOLIO_APP.SUI_VISION]: "SuiVision",
  [PORTFOLIO_APP.APTOS_EXPLORER]: "Aptos Explorer",
  [PORTFOLIO_APP.SOL_SCAN]: "Solscan",
};

export const PORTFOLIO_APP_URL = {
  [PORTFOLIO_APP.DEBANK]: "https://debank.com",
  [PORTFOLIO_APP.SUI_VISION]: "https://suivision.xyz",
  [PORTFOLIO_APP.APTOS_EXPLORER]: "https://explorer.aptoslabs.com",
  [PORTFOLIO_APP.SOL_SCAN]: "https://solscan.io",
};

// telegram
export const TELEGRAM_BOT = {
  COMMAND_CONNECT_BOT: "connect_bot",
  COMMAND_GET_ALL_CAMPAIGN: "get_all_campaign",
  COMMAND_RUN_CAMPAIGN: "run_campaign",
  COMMAND_STOP_CAMPAIGN: "stop_running_campaign",
  COMMAND_CHECK_WORKFLOW_RUNNING: "check_workflow_running",
  COMMAND_CHECK_WORKFLOW_RUNNING_RES: "check_workflow_running_response",
  ACTION_RUN_CAMPAIGN: "run_campaign_",
  ACTION_RUN_A_CAMPAIGN: "run_a_campaign_",
  ACTION_RUN_WORKFLOW: "run_workflow_",
  ACTION_RUN_WORKFLOW_USING_TELEGRAM: "run_workflow_using_telegram",
  ACTION_STOP_CAMPAIGN_USING_TELEGRAM: "stop_campaign_using_telegram",
  ACTION_ENTER_ENCRYPT_KEY: "enter_encrypt_key_campaign",
  ACTION_SKIP_ENCRYPT_KEY: "skip_encrypt_key_campaign",
  ACTION_SET_VARIABLES: "set_variables_",
  ACTION_SKIP_VARIABLES: "skip_variables_",
  ACTION_SET_A_VARIABLE: "set_a_var_",
  ACTION_NEXT_STEP_VARIABLE: "next_step_var_",
  ACTION_SET_ALL_VARIABLES: "set_all_var_",
  ACTION_QUICK_RUN: "quick_run_",
  ACTION_RERUN: "rerun_",
  ACTION_BACK_TO_STEP1: "back_step1_",
  ACTION_BACK_TO_VARLIST: "back_varlist_",
  ACTION_BACK_TO_ENCRYPT: "back_encrypt_",
  ACTION_CONFIRM_RUN: "confirm_run_",
  ACTION_CANCEL_RUN: "cancel_run_",
  ACTION_SEARCH_CAMPAIGN: "search_campaign_",
  ACTION_YES: "yes",
  ACTION_NO: "no",
};

export const PROFILE_TYPE = {
  ALL_PROFILE: "ALL_PROFILE",
  CUSTOM_SELECT: "CUSTOM_SELECT",
};

export const NETWORK_PROTOCOL = {
  HTTP: "HTTP",
  HTTPS: "HTTPS",
};

export const LIST_NETWORK_PROTOCOL = [
  { value: NETWORK_PROTOCOL.HTTP, prefix: "http://" },
  { value: NETWORK_PROTOCOL.HTTPS, prefix: "https://" },
];

export const USER_AGENT_CATEGORY = {
  MACOS: "MACOS",
  WINDOW: "WINDOW",
};

export enum COMPARISION_EXPRESSION {
  LARGER = "LARGER",
  SMALLER = "SMALLER",
  EQUAL = "EQUAL",
  NOT_EQUAL = "NOT_EQUAL",
}

export enum MATH_EQUATION {
  ADD = "ADD",
  SUBSTRACT = "SUBSTRACT",
  MULTIPLY = "MULTIPLY",
  DEVIDE = "DEVIDE",
}

export const BOOLEAN_RESULT = {
  TRUE: "TRUE",
  FALSE: "FALSE",
};

export const APP_PROTOCOL_NAME = "keeperagent";

export const WALLET_VARIABLE = {
  WALLET_ADDRESS: "WALLET_ADDRESS",
  WALLET_PHRASE: "WALLET_PHRASE",
  WALLET_PRIVATE_KEY: "WALLET_PRIVATE_KEY",
};

export const SORT_ORDER = {
  DESC: "desc",
  ASC: "asc",
};

export enum IMPORT_WALLET_TYPE {
  IMPORT_BY_SEED_PHRASE = "IMPORT_BY_SEED_PHRASE",
  IMPORT_BY_PRIVATE_KEY = "IMPORT_BY_PRIVATE_KEY",
}

export const IMPORT_WALLET_TYPE_NAME = {
  [IMPORT_WALLET_TYPE.IMPORT_BY_SEED_PHRASE]: "Seed phrase",
  [IMPORT_WALLET_TYPE.IMPORT_BY_PRIVATE_KEY]: "Private key",
};
export const RABBY_ADD_NETWORK_TYPE = {
  MANUALY: "MANUALY",
  FROM_CHAINLIST: "FROM_CHAINLIST",
};

export const SCHEDULE_REPEAT = {
  NO_REPEAT: "NO_REPEAT",
  EVERY_DAY: "EVERY_DAY",
  ODD_DAY: "ODD_DAY",
  EVEN_DAY: "EVEN_DAY",
};

export const SCHEDULE_REPEAT_PER_DAY = {
  ONCE_PER_DAY: "ONCE_PER_DAY",
  MANY_TIME_PER_DAY: "MANY_TIME_PER_DAY",
};

export const SELECT_TOKEN_OUTPUT = {
  SELECTED_TOKEN_NAME: "SELECTED_TOKEN_NAME",
  SELECTED_TOKEN_ADDRESS: "SELECTED_TOKEN_ADDRESS",
};

export const SELECT_CHAIN_OUTPUT = {
  SELECTED_CHAIN_NAME: "SELECTED_CHAIN_NAME",
  SELECTED_CHAIN_TOKEN_NAME: "SELECTED_CHAIN_TOKEN_NAME",
  SELECTED_CHAIN_TOKEN_ADDRESS: "SELECTED_CHAIN_TOKEN_ADDRESS",
};

export enum FOLLOW_TWITTER_ACTION {
  FOLLOW = "FOLLOW",
  UNFOLLOW = "UNFOLLOW",
}
export enum RETEET_TWITTER_ACTION {
  RETWEET = "RETWEET",
  UNDO_RETWEET = "UNDO_RETWEET",
}
export enum LIKE_TWITTER_ACTION {
  LIKE = "LIKE",
  UNLIKE = "UNLIKE",
}

export const SCHEDULE_LOG_ACTION = {
  JOB_START: "JOB_START",
  JOB_COMPLETED: "JOB_COMPLETED",
  JOB_TIMEOUT: "JOB_TIMEOUT",
};

export const UNABLE_TO_GET_PROXY = "Unable to get proxy";
export enum PROFILE_STATUS {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
}

// variable name of Workflow Node
export const CURRENT_TOKEN_PRICE = "CURRENT_TOKEN_PRICE";
export const CURRENT_TOKEN_MARKETCAP = "CURRENT_TOKEN_MARKETCAP";

export const IS_WALLET_EXIST = "IS_WALLET_EXIST";
export const IS_RESOURCE_EXIST = "IS_RESOURCE_EXIST";

export const DEFAULT_EXECUTE_CODE_VARIABLE = "EXECUTED_RESULT";
export const SNIPE_CONTRACT_BLOCK_NUMBER = "SNIPE_CONTRACT_BLOCK_NUMBER";
export const SNIPE_CONTRACT_TX_HASH = "SNIPE_CONTRACT_TX_HASH";
export const SNIPE_CONTRACT_LOG_INDEX = "SNIPE_CONTRACT_LOG_INDEX";
export const SNIPE_CONTRACT_CONTRACT_ADDRESS =
  "SNIPE_CONTRACT_CONTRACT_ADDRESS";
export const CUSTOM_CHAIN_ID = {
  SOLANA: -1,
  SUI: -2,
  APTOS: -3,
  TON: -4,
};
export enum PRICE_DATA_SOURCE {
  COINGECKO = "COINGECKO",
  DEXSCREENER = "DEXSCREENER",
}

export const EXTENSION = {
  METAMASK: "METAMASK",
  PHANTOM_WALLET: "PHANTOM_WALLET",
  RABBY_WALLET: "RABBY_WALLET",
  MARTIAN_WALLET: "MARTIAN_WALLET",
};

export const EXTENSION_NAME_SEARCH = {
  [EXTENSION.METAMASK]: "metamask",
  [EXTENSION.PHANTOM_WALLET]: "Phantom",
  [EXTENSION.RABBY_WALLET]: "Rabby",
  [EXTENSION.MARTIAN_WALLET]: "Martian",
};

export enum NODE_STATUS {
  RUN = "RUN",
  STOP = "STOP",
  INVALID = "INVALID",
}

export enum ENCRYPT_MODE {
  NO_ENSCRYPT = "NO_ENSCRYPT",
  ENCRYPT = "ENCRYPT",
}

export enum NODE_TYPE {
  CUSTOM_NODE = "CUSTOM_NODE",
  START_NODE = "START_NODE",
  END_NODE = "END_NODE",
  COMMENT_NODE = "COMMENT_NODE",
}

export enum HTTP_METHOD {
  GET = "GET",
  POST = "POST",
  PUT = "PUT",
  DELETE = "DELETE",
}

export const ERROR_PERMISSION_TO_RUN_NODE =
  "Please upgrade your pricing tier to run this Node";

export const RABBY_GAS_MODE = {
  NORMAL: "NORMAL",
  FAST: "FAST",
  INSTANT: "INSTANT",
  CUSTOM: "CUSTOM",
};

export enum METAMASK_GAS_MODE {
  LOW = "LOW",
  MARKET = "MARKET",
  AGGRESSIVE = "AGGRESSIVE",
  ADVANCED = "ADVANCED",
}

export enum CONTRACT_SNIPER_MODE {
  ONE_EVENT_ALL_PROFILE = "ONE_EVENT_ALL_PROFILE",
  ONE_EVENT_ONE_PROFILE = "ONE_EVENT_ONE_PROFILE",
}

export enum TELEGRAM_SNIPER_MODE {
  ONE_EVENT_ALL_PROFILE = "ONE_EVENT_ALL_PROFILE",
  ONE_EVENT_ONE_PROFILE = "ONE_EVENT_ONE_PROFILE",
}

export const MAP_KYBER_ROUTER_ADDRESS_BY_CHAIN: { [key: string]: string } = {
  ethereum: "0x6131b5fae19ea4f9d964eac0408e4408b66337b5",
  bsc: "0x6131b5fae19ea4f9d964eac0408e4408b66337b5",
  arbitrum: "0x6131b5fae19ea4f9d964eac0408e4408b66337b5",
  polygon: "0x6131b5fae19ea4f9d964eac0408e4408b66337b5",
  optimism: "0x6131b5fae19ea4f9d964eac0408e4408b66337b5",
  avalanche: "0x6131b5fae19ea4f9d964eac0408e4408b66337b5",
  base: "0x6131b5fae19ea4f9d964eac0408e4408b66337b5",
  zksync: "0x3f95ef3f2eaca871858dbe20a93c01daf6c2e923",
  linea: "0x6131b5fae19ea4f9d964eac0408e4408b66337b5",
  scroll: "0x6131b5fae19ea4f9d964eac0408e4408b66337b5",
  mantle: "0x6131b5fae19ea4f9d964eac0408e4408b66337b5",
  blast: "0x6131b5fae19ea4f9d964eac0408e4408b66337b5",
  sonic: "0x6131b5fae19ea4f9d964eac0408e4408b66337b5",
  unichain: "0x6131b5fae19ea4f9d964eac0408e4408b66337b5",
  berachain: "0x6131b5fae19ea4f9d964eac0408e4408b66337b5",
  ronin: "0x6131b5fae19ea4f9d964eac0408e4408b66337b5",
  monad: "0x6131b5fae19ea4f9d964eac0408e4408b66337b5",
  plasma: "0x6131b5fae19ea4f9d964eac0408e4408b66337b5",
  hyperevm: "0x6131b5fae19ea4f9d964eac0408e4408b66337b5",
};

export enum KYBERSWAP_CHAIN_KEY {
  ETHEREUM = "ethereum",
  BSC = "bsc",
  ARBITRUM = "arbitrum",
  POLYGON = "polygon",
  OPTIMISM = "optimism",
  AVALANCHE = "avalanche",
  BASE = "base",
  ZKSYNC = "zksync",
  LINEA = "linea",
  SCROLL = "scroll",
  MANTLE = "mantle",
  BLAST = "blast",
  SONIC = "sonic",
  UNICHAIN = "unichain",
  BERACHAIN = "berachain",
  RONIN = "ronin",
  MONAD = "monad",
  PLASMA = "plasma",
  HYPEREVM = "hyperevm",
}

export const EVM_CHAIN_ID: Record<string, number> = {
  [KYBERSWAP_CHAIN_KEY.ETHEREUM]: 1,
  [KYBERSWAP_CHAIN_KEY.BSC]: 56,
  [KYBERSWAP_CHAIN_KEY.POLYGON]: 137,
  [KYBERSWAP_CHAIN_KEY.ARBITRUM]: 42161,
  [KYBERSWAP_CHAIN_KEY.OPTIMISM]: 10,
  [KYBERSWAP_CHAIN_KEY.AVALANCHE]: 43114,
  [KYBERSWAP_CHAIN_KEY.BASE]: 8453,
  [KYBERSWAP_CHAIN_KEY.ZKSYNC]: 324,
  [KYBERSWAP_CHAIN_KEY.LINEA]: 59144,
  [KYBERSWAP_CHAIN_KEY.SCROLL]: 534352,
  [KYBERSWAP_CHAIN_KEY.MANTLE]: 5000,
  [KYBERSWAP_CHAIN_KEY.BLAST]: 81457,
  [KYBERSWAP_CHAIN_KEY.SONIC]: 146,
  [KYBERSWAP_CHAIN_KEY.UNICHAIN]: 130,
  [KYBERSWAP_CHAIN_KEY.BERACHAIN]: 80094,
  [KYBERSWAP_CHAIN_KEY.RONIN]: 2020,
};

export const TOOL_KEYS = {
  // Subagents
  TRANSACTION_AGENT: "transaction_agent",
  CODE_EXECUTION_AGENT: "code_execution_agent",
  WORKFLOW_AGENT: "workflow_agent",
  RESEARCH_AGENT: "research_agent",
  SCHEDULER_AGENT: "scheduler_agent",
  TASK_MANAGEMENT_AGENT: "task_management_agent",
  TEAM_MAILBOX_AGENT: "team_mailbox_agent",
  DATA_MANAGEMENT_AGENT: "data_management_agent",
  VISUALIZATION_AGENT: "visualization_agent",
  // Built-in tools
  LS: "ls",
  READ_FILE: "read_file",
  WRITE_FILE: "write_file",
  GREP: "grep",
  FIND: "find",
  EXECUTE: "execute",
  TASK: "task",
  WRITE_TODOS: "write_todos",
  // Transaction tools
  SWAP_ON_JUPITER: "swap_on_jupiter",
  SWAP_ON_KYBERSWAP: "swap_on_kyberswap",
  TRANSFER_SOLANA_TOKEN: "transfer_solana_token",
  GET_SOLANA_TOKEN_BALANCE: "get_solana_token_balance",
  GET_EVM_TOKEN_BALANCE: "get_evm_token_balance",
  GET_TOKEN_PRICE: "get_token_price",
  LAUNCH_PUMPFUN_TOKEN: "launch_pumpfun_token",
  LAUNCH_BONKFUN_TOKEN: "launch_bonkfun_token",
  BROADCAST_TRANSACTION_EVM: "broadcast_transaction_evm",
  BROADCAST_TRANSACTION_SOLANA: "broadcast_transaction_solana",
  // Wallet & data tools
  CREATE_WALLET_GROUP: "create_wallet_group",
  GENERATE_WALLETS_FOR_GROUP: "generate_wallets_for_group",
  CREATE_RESOURCE_GROUP: "create_resource_group",
  LIST_RESOURCE_GROUPS: "list_resource_groups",
  BULK_ADD_RESOURCES: "bulk_add_resources",
  BULK_UPDATE_RESOURCES: "bulk_update_resources",
  QUERY_RESOURCES: "query_resources",
  // Code execution
  WRITE_JAVASCRIPT: "write_javascript",
  EXECUTE_JAVASCRIPT: "execute_javascript",
  // Workflow tools
  SEARCH_CAMPAIGNS: "search_campaigns",
  SEARCH_WORKFLOWS: "search_workflows",
  RUN_WORKFLOW: "run_workflow",
  STOP_WORKFLOW: "stop_workflow",
  CHECK_WORKFLOW_STATUS: "check_workflow_status",
  // Research tools
  WEB_SEARCH_TAVILY: "web_search_tavily",
  WEB_SEARCH_EXA: "web_search_exa",
  WEB_EXTRACT_TAVILY: "web_extract_tavily",
  FIND_SIMILAR_EXA: "find_similar_exa",
  // Scheduler tools
  CREATE_AGENT_SCHEDULE: "create_agent_schedule",
  LIST_AGENT_SCHEDULES: "list_agent_schedules",
  UPDATE_AGENT_SCHEDULE: "update_agent_schedule",
  DELETE_AGENT_SCHEDULE: "delete_agent_schedule",
  PAUSE_AGENT_SCHEDULE: "pause_agent_schedule",
  RESUME_AGENT_SCHEDULE: "resume_agent_schedule",
  RUN_AGENT_SCHEDULE_NOW: "run_agent_schedule_now",
  // Agent task tools
  LIST_AGENT_TASKS: "list_agent_tasks",
  GET_AGENT_TASK: "get_agent_task",
  CREATE_AGENT_TASK: "create_agent_task",
  UPDATE_AGENT_TASK: "update_agent_task",
  DELETE_AGENT_TASK: "delete_agent_task",
  // Mailbox tools
  SEND_MESSAGE: "send_message",
  READ_MESSAGES: "read_messages",
  ACKNOWLEDGE_MESSAGE: "acknowledge_message",
  // Planning tools
  REQUEST_APPROVAL: "request_approval",
  CONFIRM_APPROVAL: "confirm_approval",
  // Team tools
  CREATE_AGENT_TEAM: "create_agent_team",
  GET_TEAM_PROGRESS: "get_team_progress",
  DELEGATE_TASK: "delegate_task",
  // Visualization tools
  RENDER_CHART: "render_chart",
  // Calculator
  CALCULATE: "calculate",
} as const;

export const TOOL_DISPLAY_NAMES: Record<string, string> = {
  // Subagent names
  [TOOL_KEYS.TRANSACTION_AGENT]: "Transaction subagent",
  [TOOL_KEYS.CODE_EXECUTION_AGENT]: "Code Execution subagent",
  [TOOL_KEYS.WORKFLOW_AGENT]: "Workflow subagent",
  [TOOL_KEYS.RESEARCH_AGENT]: "Research subagent",
  [TOOL_KEYS.SCHEDULER_AGENT]: "Scheduler subagent",
  [TOOL_KEYS.TASK_MANAGEMENT_AGENT]: "Task management subagent",
  [TOOL_KEYS.TEAM_MAILBOX_AGENT]: "Mailbox subagent",
  [TOOL_KEYS.DATA_MANAGEMENT_AGENT]: "Data management subagent",

  // Deepagents built-in tools
  [TOOL_KEYS.LS]: "Browse files",
  [TOOL_KEYS.READ_FILE]: "Read file",
  [TOOL_KEYS.WRITE_FILE]: "Write file",
  [TOOL_KEYS.GREP]: "Search files",
  [TOOL_KEYS.FIND]: "Find files",
  [TOOL_KEYS.EXECUTE]: "Run command",
  [TOOL_KEYS.TASK]: "Run subagent",
  [TOOL_KEYS.WRITE_TODOS]: "Todo list",

  // Calculator
  [TOOL_KEYS.CALCULATE]: "Calculate",

  // Transaction tools
  [TOOL_KEYS.SWAP_ON_JUPITER]: "Swap on Jupiter",
  [TOOL_KEYS.SWAP_ON_KYBERSWAP]: "Swap on KyberSwap",
  [TOOL_KEYS.TRANSFER_SOLANA_TOKEN]: "Transfer Solana token",
  [TOOL_KEYS.GET_SOLANA_TOKEN_BALANCE]: "Get Solana token balance",
  [TOOL_KEYS.GET_EVM_TOKEN_BALANCE]: "Get EVM token balance",
  [TOOL_KEYS.GET_TOKEN_PRICE]: "Get token price",
  [TOOL_KEYS.LAUNCH_PUMPFUN_TOKEN]: "Launch Pump.fun token",
  [TOOL_KEYS.LAUNCH_BONKFUN_TOKEN]: "Launch Bonk.fun token",
  [TOOL_KEYS.BROADCAST_TRANSACTION_EVM]: "Broadcast EVM transaction",
  [TOOL_KEYS.BROADCAST_TRANSACTION_SOLANA]: "Broadcast Solana transaction",

  // Wallet & data tools
  [TOOL_KEYS.CREATE_WALLET_GROUP]: "Create wallet group",
  [TOOL_KEYS.GENERATE_WALLETS_FOR_GROUP]: "Generate wallets",
  [TOOL_KEYS.CREATE_RESOURCE_GROUP]: "Create resource group",
  [TOOL_KEYS.LIST_RESOURCE_GROUPS]: "List resource groups",
  [TOOL_KEYS.BULK_ADD_RESOURCES]: "Add resources",
  [TOOL_KEYS.BULK_UPDATE_RESOURCES]: "Update resources",
  [TOOL_KEYS.QUERY_RESOURCES]: "Query resources",

  // Code execution
  [TOOL_KEYS.WRITE_JAVASCRIPT]: "Write JavaScript",
  [TOOL_KEYS.EXECUTE_JAVASCRIPT]: "Execute JavaScript",

  // Workflow tools
  [TOOL_KEYS.SEARCH_CAMPAIGNS]: "Search campaigns",
  [TOOL_KEYS.SEARCH_WORKFLOWS]: "Search workflows",
  [TOOL_KEYS.RUN_WORKFLOW]: "Run workflow",
  [TOOL_KEYS.STOP_WORKFLOW]: "Stop workflow",
  [TOOL_KEYS.CHECK_WORKFLOW_STATUS]: "Check workflow status",

  // Research tools
  [TOOL_KEYS.WEB_SEARCH_TAVILY]: "Web search (Tavily)",
  [TOOL_KEYS.WEB_SEARCH_EXA]: "Web search (Exa)",
  [TOOL_KEYS.WEB_EXTRACT_TAVILY]: "Web extract (Tavily)",
  [TOOL_KEYS.FIND_SIMILAR_EXA]: "Find similar (Exa)",

  // Scheduler tools
  [TOOL_KEYS.CREATE_AGENT_SCHEDULE]: "Create schedule",
  [TOOL_KEYS.LIST_AGENT_SCHEDULES]: "List schedules",
  [TOOL_KEYS.UPDATE_AGENT_SCHEDULE]: "Update schedule",
  [TOOL_KEYS.DELETE_AGENT_SCHEDULE]: "Delete schedule",
  [TOOL_KEYS.PAUSE_AGENT_SCHEDULE]: "Pause schedule",
  [TOOL_KEYS.RESUME_AGENT_SCHEDULE]: "Resume schedule",
  [TOOL_KEYS.RUN_AGENT_SCHEDULE_NOW]: "Run schedule now",

  // Agent task tools
  [TOOL_KEYS.LIST_AGENT_TASKS]: "List tasks",
  [TOOL_KEYS.GET_AGENT_TASK]: "Get task",
  [TOOL_KEYS.CREATE_AGENT_TASK]: "Create task",
  [TOOL_KEYS.UPDATE_AGENT_TASK]: "Update task",
  [TOOL_KEYS.DELETE_AGENT_TASK]: "Delete task",

  // Mailbox tools
  [TOOL_KEYS.SEND_MESSAGE]: "Send message",
  [TOOL_KEYS.READ_MESSAGES]: "Read messages",
  [TOOL_KEYS.ACKNOWLEDGE_MESSAGE]: "Acknowledge message",

  // Planning tools
  [TOOL_KEYS.REQUEST_APPROVAL]: "Request approval",
  [TOOL_KEYS.CONFIRM_APPROVAL]: "Confirm approval",

  // Team tools
  [TOOL_KEYS.CREATE_AGENT_TEAM]: "Create agent team",
  [TOOL_KEYS.GET_TEAM_PROGRESS]: "Get team progress",
  [TOOL_KEYS.DELEGATE_TASK]: "Delegate task",

  // Visualization
  [TOOL_KEYS.VISUALIZATION_AGENT]: "Visualization subagent",
  [TOOL_KEYS.RENDER_CHART]: "Render chart",
};

export const getToolDisplayName = (toolName: string): string =>
  TOOL_DISPLAY_NAMES[toolName] ||
  toolName.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
