import { runWalletGroupController } from "./controller/walletGroup";
import { runWalletController } from "./controller/wallet";
import { runStatisticController } from "./controller/statistic";
import { runWorkflowRunnerController } from "./controller/workflowRunner";
import { runWorkflowController } from "./controller/workflow";
import { runResourceGroupController } from "./controller/resourceGroup";
import { resourceController } from "./controller/resource";
import { proxyIpController } from "./controller/proxyIp";
import { proxyIpGroupController } from "./controller/proxyIpGroup";
import { proxyController } from "./controller/proxy";
import { profileGroupController } from "./controller/profileGroup";
import { profileController } from "./controller/profile";
import { perferenceController } from "./controller/preference";
import { nodeEndpointGroupController } from "./controller/nodeEndpointGroup";
import { nodeEndpointController } from "./controller/nodeEndpoint";
import { extensionController } from "./controller/extension";
import { dialogController } from "./controller/dialog";
import { databaseController } from "./controller/database";
import { campaignProfileController } from "./controller/campaignProfile";
import { campaignController } from "./controller/campaign";
import { windowController } from "./controller/window";
import { fileController } from "./controller/file";
import { browserController } from "./controller/browser";
import { telegramController } from "./controller/telegram";
import { userLogController } from "./controller/userLog";
import { runScheduleController } from "./controller/schedule";
import { runJobController } from "./controller/job";
import { runScheduleLogController } from "./controller/scheduleLog";
import { masterPasswordController } from "./controller/masterPassword";
import { runSecretKeyController } from "./controller/secretKeyCache";
import { telegramBotService } from "./service/telegramBot";
import { scheduleManager } from "./schedule";
import { searchController } from "./controller/search";
import { agentController } from "./controller/appAgent";
import { mcpServerController } from "./controller/mcpServer";
import { agentSkillController } from "./controller/agentSkill";
import { chatHistoryController } from "./controller/chatHistory";
import { nodeSecretController } from "./controller/nodeSecret";
import { authStorageController } from "./controller/authStorage";

const runMainProcess = () => {
  telegramController();
  runWalletGroupController();
  runWalletController();
  runStatisticController();
  runWorkflowRunnerController();
  runWorkflowController();
  runResourceGroupController();
  resourceController();
  proxyIpController();
  proxyController();
  profileGroupController();
  profileController();
  perferenceController();
  nodeEndpointGroupController();
  nodeEndpointController();
  extensionController();
  dialogController();
  databaseController();
  campaignProfileController();
  campaignController();
  proxyIpGroupController();
  windowController();
  fileController();
  browserController();
  userLogController();
  runScheduleController();
  runJobController();
  runScheduleLogController();
  masterPasswordController();
  runSecretKeyController();
  searchController();
  agentController();
  mcpServerController();
  agentSkillController();
  chatHistoryController();
  nodeSecretController();
  authStorageController();

  scheduleManager.start();
  telegramBotService.start();
};

export { runMainProcess };
