import { runWalletGroupController } from "./controller/walletGroup";
import { runWalletController } from "./controller/wallet";
import { runStatisticController } from "./controller/statistic";
import { runWorkflowRunnerController } from "./controller/workflowRunner";
import { runWorkflowController } from "./controller/workflow";
import { runResourceGroupController } from "./controller/resourceGroup";
import { resourceController } from "./controller/resource";
import { staticProxyController } from "./controller/staticProxy";
import { staticProxyGroupController } from "./controller/staticProxyGroup";
import { profileGroupController } from "./controller/profileGroup";
import { profileController } from "./controller/profile";
import {
  perferenceController,
  applyScreenCaptureProtection,
} from "./controller/preference";
import { nodeEndpointGroupController } from "./controller/nodeEndpointGroup";
import { nodeEndpointController } from "./controller/nodeEndpoint";
import { extensionController } from "./controller/extension";
import { dialogController } from "./controller/dialog";
import { databaseController } from "./controller/database";
import { campaignProfileController } from "./controller/campaignProfile";
import { campaignController } from "./controller/campaign";
import { windowController } from "./controller/window";
import { fileController } from "./controller/file";
import { browserController } from "./controller/browser";
import { telegramController } from "./controller/telegram";
import { runScheduleController } from "./controller/schedule";
import { runJobController } from "./controller/job";
import { masterPasswordController } from "./controller/masterPassword";
import { runEncryptKeyController } from "./controller/encryptKeyCache";
import { telegramBotService } from "./chatGateway/adapters/telegram";
import { whatsappService } from "./chatGateway/adapters/whatsapp";
import { scheduleManager } from "./schedule";
import { agentTaskScheduler } from "./service/agentJobScheduler";
import { searchController } from "./controller/search";
import { agentController } from "./controller/appAgent";
import { mcpServerController } from "./controller/mcpServer";
import { agentSkillController } from "./controller/agentSkill";
import { settingController } from "./controller/setting";
import { chatHistoryController } from "./controller/chatHistory";
import { nodeSecretController } from "./controller/nodeSecret";
import { authStorageController } from "./controller/authStorage";
import { whatsappController } from "./controller/whatsapp";
import { agentProfileController } from "./controller/agentProfile";
import { mcpTokenController } from "./controller/mcpToken";
import { agentTaskController } from "./controller/agentTask";
import { appLogController } from "./controller/appLog";
import { agentTaskDispatcher } from "./service/agentTaskDispatcher";
import { licenseService } from "./service/licenseService";
import { keeperMcpServer } from "./mcpServer";

const runMainProcess = () => {
  licenseService.initialize();
  telegramController();
  runWalletGroupController();
  runWalletController();
  runStatisticController();
  runWorkflowRunnerController();
  runWorkflowController();
  runResourceGroupController();
  resourceController();
  staticProxyController();
  profileGroupController();
  profileController();
  perferenceController();
  nodeEndpointGroupController();
  nodeEndpointController();
  extensionController();
  dialogController();
  databaseController();
  campaignProfileController();
  campaignController();
  staticProxyGroupController();
  windowController();
  fileController();
  browserController();
  runScheduleController();
  runJobController();
  masterPasswordController();
  runEncryptKeyController();
  searchController();
  agentController();
  mcpServerController();
  agentSkillController();
  settingController();
  chatHistoryController();
  nodeSecretController();
  authStorageController();
  whatsappController();
  agentProfileController();
  mcpTokenController();
  agentTaskController();
  appLogController();

  scheduleManager.start();
  whatsappService.start();
  telegramBotService.start();

  agentTaskScheduler.init();
  agentTaskDispatcher.startStaleWorker();
  agentTaskDispatcher.recoverOnStartup();
  agentTaskDispatcher.dispatch();

  keeperMcpServer.startIfEnabled();
  applyScreenCaptureProtection();
};

export { runMainProcess };
