export const TEMP_PROFILENAME = "temp";
export const DEFAULT_TIMEOUT = 10000; // 10s
export const DEFAULT_EXTENSION_TIMEOUT = 35000; // 35s
export enum NODE_ACTION {
  RERUN_THREAD = "RERUN_THREAD",
  PAUSE_THREAD = "PAUSE_THREAD",
  TERMINATE_THREAD_AND_MARK_DONE = "TERMINATE_THREAD_AND_MARK_DONE",
  CONTINUE_RUN = "CONTINUE_RUN",
}

export const MESSAGE_TURN_OFF_PROFILE = "skip this profile";
export const MESSAGE_CONDITION_RETURN_FALSE = "condition returns FALSE";
